### ISSUE TITLE
Error: missing package name

### ISSUE THREAD

**Issue by davidkuridza** [tmthrgd/go-bindata#10]
[GenerateOptions][0] struct is defined like this:

```go
type GenerateOptions struct {
	// Name of the package to use. Defaults to 'main'.
	Package string
...
```

However, doing something like this, fails with a [validation error][1]:

```go
files.Generate(os.Stdout, &bindata.GenerateOptions{
	Debug: true,
})
```

Based on the comment `Defaults to 'main'.`, I assume even if `GenerateOptions` is present without `Package`, default value should be set.

Just wanted to clarify it before opening a pull request.

[0]: https://github.com/tmthrgd/go-bindata/blob/master/config.go#L73-L75
[1]: https://github.com/tmthrgd/go-bindata/blob/master/config.go#L184-L186

**Comment by tmthrgd** [comment]
This is indeed a bug. This can very easily be seen as either a mistake in the `GenerateOptions` documentation or a bug in the `(*GenerateOptions).validate` method. I'm far more inclined to see this as a documentation mistake. I actively want to discourage people from putting assets into the main package, they should go into an internal subpackage. (This is for various reasons, one of which is faster compilation).

**Comment by tmthrgd** [comment]
If you wish to open a pull request, I'd suggest it be to correct the documentation.
